### ISSUE TITLE
eval: use of retry tool in build scripts

### ISSUE THREAD

**Issue by ssbarnea** [ansible/team-devtools#231]
As we often encounter some operations that fail for random factors like network access, it would be useful to have a simple way to retry some build commands.

One such tool is [retry](https://github.com/minfrin/retry), which does not seem to be available on Redhat platforms anymore. Maybe we can identify an alternative or remediate it.

```[tasklist]
### Tasks
- [x] ubuntu 24.04
- [x] macos via brew
- [ ] [fedora](https://github.com/minfrin/retry/issues/22)
- [ ] ubi8
- [ ] ubi9
- [ ] asdf (could be an acceptable alternative to rpms)
- [x] nix
```

**Comment by minfrin** [comment]
Retry is new, and has never been in Fedora. The ticket to add it is here, but the process went wrong somewhere:

https://bugzilla.redhat.com/show_bug.cgi?id=2017119

**Comment by minfrin** [comment]
Retry is now in Fedora.

<img width="602" height="483" alt="Image" src="https://github.com/user-attachments/assets/67737362-d64c-4049-ac8b-77f51badde4b" />
