### ISSUE TITLE
APP 2.4 Tracker

### ISSUE THREAD

**Issue by ssbarnea** [ansible/team-devtools#95]
All remailing items listed below need to be translated to tickets which are assigned to devtools project with aap:2.4 field, so they will list on https://github.com/orgs/ansible/projects/86/views/1 board.

We should move anything that is undefined to a bottom checklist, as we cannot plan for stuff that we do not know, like "fix reported bugs".

## Other ideas or areas to explore (not directly actionable)
- [ ] Pytest (Content testing strategy):
- [ ] (H/C) Define the “Content testing strategy” per persona and start identifying software needs
- [ ] Molecule
- [ ] ansible-test (unit/integration)
- [x] Pytest-ansible (https://github.com/ansible-community/pytest-ansible)
- [x] Pytest-ansible-unit (https://github.com/ansible-community/pytest-ansible-units)
- [x] Pytest-molecule (https://github.com/ansible-community/pytest-molecule)
- [ ] Pytest-ansible-integration (https://github.com/ansible-network/pytest-ansible-network-integration)
- [ ] Look closer at ansible-test sanity to see if parts can be replicated in other tools.
- [ ] Test output artifact/output/report (needed for validated content)
- [ ] Switch from sphinx to not-sphinx (python projects)
- [ ] Remove API docs from python projects, replace with contributor docs suggesting vscode and it’s native python code doc support
- Ongoing rule authoring and profile tuning - Profile [List](https://ansible-lint.readthedocs.io/profiles/).
- Open issues on new rules/profiles
- Ensure no rule is added w/o documentation
- What Telemetry data to be collected from the user environment - Requires discussion with BU.
-  Option-1: Allow a unified settings file for ansible-navigator, ansible-lint and VSCode extension
